name: ociregistry
version: 0.0.1
resources:
  # const latest = new ociregistry.ImageVersion("nginx", { imageRepo: "library/nginx", constraint: ">=1.20.0" });
  ociregistry:index:ImageVersion:
    properties:
      imageRepo:
        type: string
      constraint:
        type: string
      imageRef:
        type: string
    required:
      - imageRepo
      - constraint
      - imageRef
    inputProperties:
      imageRepo:
        type: string
      constraint:
        type: string
    requiredInputs:
      - imageRepo
      - constraint
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/squaremo/pulumi-ociregistry-provider/sdk/go/ociregistry
  nodejs:
    dependencies:
      '@pulumi/pulumi': ^3.0.0
  python:
    requires:
      pulumi: '>=3.0.0,<4.0.0'
